# Generated by Django 4.2.5 on 2024-03-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_service', models.CharField(blank=True, choices=[('construction', 'Construction'), ('logistics', 'Logistics'), ('grantfunding', 'Grant Funding for Distressed Enterprises')], max_length=50, null=True)),
                ('enterprise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('enterprise_address', models.TextField(blank=True, null=True)),
                ('primary_representative', models.CharField(blank=True, max_length=100, null=True)),
                ('num_employees_contributing_to_uif', models.IntegerField(blank=True, null=True)),
                ('uif_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_clearance_certificate', models.BooleanField(default=False)),
                ('enterprise_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('audited_statements', models.BooleanField(default=False)),
                ('accounting_firm_or_accountant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('management_accounts_and_cash_flow_projections', models.BooleanField(default=False)),
                ('field_of_operation', models.CharField(blank=True, max_length=100, null=True)),
                ('years_in_operation', models.IntegerField(blank=True, null=True)),
                ('future_orders_or_new_business_areas', models.TextField(blank=True, null=True)),
                ('agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
